# Lab Work - 2.4


# Q1 Understanding the MLR Equation

In [1]:
# Mathematical Equation:
# y = β0 + β1x1 + β2x2

print("y = β0 + β1x1 + β2x2")

print("\nVariable Mapping:")
print("x1 = Experience")
print("x2 = Education Level")
print("y = Salary")

experience = 5
education = 3

b0 = 5000
b1 = 2000
b2 = 1500

salary = b0 + b1 * experience + b2 * education

print("\nSample Prediction=", salary)

y = β0 + β1x1 + β2x2

Variable Mapping:
x1 = Experience
x2 = Education Level
y = Salary

Sample Prediction= 19500


# Q2 Matrix Representation of Data

In [2]:
import numpy as np

X = np.array([[1, 1, 2], [1, 2, 3], [1, 3, 2], [1, 4, 4], [1, 5, 3]])

y = np.array([10000, 15000, 18000, 25000, 28000])

print("Feature Matrix X:")
print(X)

print("\nTarget y:")
print(y)

print("\nShape of X:", X.shape)
print("Shape of y:", y.shape)

print("\nMatrix Equation:")
print("Y = Xβ")

Feature Matrix X:
[[1 1 2]
 [1 2 3]
 [1 3 2]
 [1 4 4]
 [1 5 3]]

Target y:
[10000 15000 18000 25000 28000]

Shape of X: (5, 3)
Shape of y: (5,)

Matrix Equation:
Y = Xβ


# Q3 Manual Prediction Using Coefficients

In [3]:
b0 = 5000
b1 = 2000
b2 = 1500

samples = np.array([[2, 1], [5, 2], [7, 4]])

print("Manual Predictions:")

for x1, x2 in samples:
    pred = b0 + b1 * x1 + b2 * x2
    print((x1, x2), "=", pred)

X = np.column_stack((np.ones(3), samples))

beta = np.array([b0, b1, b2])

prediction = X @ beta

print("\nNumPy Verification:")
print(prediction)

Manual Predictions:
(np.int64(2), np.int64(1)) = 10500
(np.int64(5), np.int64(2)) = 18000
(np.int64(7), np.int64(4)) = 25000

NumPy Verification:
[10500. 18000. 25000.]


# Q4 Understanding Bias (Intercept)

In [4]:
X = np.array([[2], [4], [6], [8]])

print("Without Bias:")
print(X)

X_bias = np.column_stack((np.ones(4), X))

print("\nWith Bias:")
print(X_bias)

print("\nβ0 shifts prediction line upward/downward")

Without Bias:
[[2]
 [4]
 [6]
 [8]]

With Bias:
[[1. 2.]
 [1. 4.]
 [1. 6.]
 [1. 8.]]

β0 shifts prediction line upward/downward


# Q5 Shape Validation in MLR

In [5]:
X = np.random.randint(1, 10, (10, 3))

beta = np.array([100, 50, 20])

print("X shape:", X.shape)
print("beta shape:", beta.shape)

y = X @ beta

print("Output shape:", y.shape)

try:
    wrong = np.random.randint(1, 10, (4,))
    X @ wrong
except Exception as e:
    print("\nShape Error:")
    print(e)

X shape: (10, 3)
beta shape: (3,)
Output shape: (10,)

Shape Error:
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)


# Q6 Real Life Dataset Mapping

In [6]:
print("x1 = House Size")
print("x2 = Number of Rooms")

print("\nRegression Equation:")
print("Price=β0+β1x1+β2x2")

X = np.array([[1, 1000, 2], [1, 1200, 3], [1, 1400, 3], [1, 1800, 4], [1, 2200, 5]])

beta = np.array([50000, 100, 20000])

predicted = X @ beta

print("\nFeature Matrix:")
print(X)

print("\nPredicted Prices:")
print(predicted)

x1 = House Size
x2 = Number of Rooms

Regression Equation:
Price=β0+β1x1+β2x2

Feature Matrix:
[[   1 1000    2]
 [   1 1200    3]
 [   1 1400    3]
 [   1 1800    4]
 [   1 2200    5]]

Predicted Prices:
[190000 230000 250000 310000 370000]
